@startuml
!pragma teoz true
!theme plain

/'
+ The World
++_ Other Characters
+++_ Edmund Bosak
+++_ Fulco Lister
+++_ Jordan Hayes
+++_ Thath
+++_ The Flaberjackles
++_ Locations
+++_ America
+++_ Europe
+++_ Kernel City
++++_ Districts
+++++_ Marez
++++++_ The Ardara
++++++_ The Server Inferno
+++++_ Olana
++++++_ Chrome Buildings
+++++_ Herresh
++++++_ Poverty
++++_ MSEP
++++_ Dits
+++++_ Water Equivalent
++++_ State of Kernel
+++++_ Kernel Army
++++_ Synth-Bioluminescence
++++_ Kernelaid
++++_ Kernelese
+++_ India
+++_ China
++_ Pickerism
+++_ The Picker
+++_ Mathematical Model
++++_ Population of the Universe
++++_ Absolute/Relative Picker Time
++++_ Gamma
+++_ Oracles
+++_ Transcendentalism
++++_ The Transcendentalists' War
+++_ Cascade Theory
++++_ Sentience Obliteration
+++_ One True Harold
+++_ Yaqut
+++_ Cultish Behavior
++++_ Controllers
++++_ Changers
++++_ Choosers
+++++_ Super-Choosers
+++++_ Mega-Choosers
+++++_ Giga-Choosers
++_ Groups
+++_ Datism
++++_ Americans
+++++_ Dylan the Ricer
+++++_ Nick Mueller
+++++_ Taylor Walsh
++++_ CDO
+++++_ Guiying Yan
+++++_ Lewis Rodney
+++++_ Mei Liao
+++++_ Tao Lei
+++++_ Zhihao Dai
++++_ Europeans
+++++_ Faycal-Monique
+++++_ Marcel Thomas
++++_ The Trashmen
+++++_ Hamza
+++++_ Ina
+++++_ Nirmala Bulan
+++++_ Rashid Al Haddad
+++++_ Sakina Nagi
++++_ 3rd Worlders
++++_ Cobalt Saber
+++++_ Aleks Bosak
+++++_ Anita
+++++_ Elliot Fetterman
+++++_ Habib Khalil
+++++_ Manoj
+++++_ Rafael Bosak
+++_ Megacorps
++++_ Tachi-Odyne
+++++_ PMC
++++++_ Homeless
++++++_ Synth-Organ Incentive Cycle
++++++_ The Magazine Mechanism
++++++_ Alexandr Matveev
++++++_ Mark Mullens
++++++_ Chae-Yeong
++++_ Altetro
+++++_ Adrian Vue
+++++_ Felix Vue
++++_ Dark Ice Corporation
+++++_ Cryobed
+++++_ Cryotank
++++_ Zilla Arms
++++_ Verflux Studios
+++++_ Neurons
++++_ Endora
++++_ Kernel Biotech
+++++_ Rice Hack
+++++_ Interface
+++_ The Cicadas
++++_ Emil Rider
++++_ Lorreta the Cougar
+++_ Hyper Churches
++++_ John Smith
+++_ Drug Runners Of Marez
+++_ Interfaced
++++_ The Natrives
+++_ Un-Interfaced
--_ Internet
---_ Gospel of the Whores
---_ Matrix Compatibility
--_ Un-Interfaced Implants
---_ Exoskeletons
---_ Microweable
--_ AI
---_ Artifical Consciousness
---_ Cybernetic Model
----_ Manifold Manipulation
---_ Discrimination (Proompt)
----_ Harrison Arkwright
---_ Human Interfacing
----_ Host Detachment
--_ Interface
---_ Installation Procedure
----_ Interface Pins
-----_ Heads
-----_ Artifical Guide Cells
-----_ Tubules
----_ Reservoirs
----_ Spider Robots
-----_ Anchoring
---_ Jack
----_ Wireless
----_ Wrist
---_ Neural Modem
----_ Modem Jacking
---_ Medicine
---_ Enhanced Combat
----_ Supression
-----_ Empathy
-----_ Pain
----_ Exaggeration
-----_ Reflexes
-----_ Senses
---_ Brain Plasticity
---_ Software
----_ Synth-Intuition
----_ Encryption
----_ Artifical Learning
-----_ Big Data (Easy)
------_ Languages
-----_ Small Data (Hard)
------_ Unique Skills
----_ Machine Control
----_ Pseudo-Meshing
-----_ Joining
----_ Hibernation 
---_ Implants
----_ Neural
-----_ Sensory (Internal)
-----_ Cognitive
-----_ Databank
----_ Physical
-----_ Sensory (External)
-----_ Endurance
-----_ Strength
--_ Matrix
---_ Adam Task
----_ Hosts and Signals
-----_ Double and Mono-Signals
-----_ Severed Signal
------_ Patches
-----_ The Discriminator
-----_ Doowee
----_ Netspace
----_ Fee
-----_ ihsotas
-----_ The Traveler
------_ Mathematical Model
----_ Program Space
-----_ The Border
-----_ Rate Limit
------_ Datafreight
-----_ Dataforts
------_ Datastream
----_ Userland
-----_ Local Space
-----_ Estation/Estates
---_ Neurons
---_ Avatars
---_ Age (_:_)
---_ Meshing
---_ Realself/Fakeself
---_ Locations
----_ Userland
-----_ The Crow's Den
-----_ Free Hub
-----_ Grandigi Hotel And Casino
-----_ Gardia
----_ Program Space
-----_ Hexridge
---_ Overlay Net
----_ The Cipher
-----_ Garlic Routing
-----_ Termination Rate
-----_ Plaintexters
-----_ Cipherists
---_ Overclocking
----_ Cryo
----_ Hyper Overclocking
-----_ Embeds And Embeddation
-----_ Hmeshing
------_ Bussard Mesh
-----_ Return Limit
----_ Merc
---_ Host Termination
----_ Frying (Overclocking)
----_ Lobotomycore/Massive Brainrot
----_ Signal Severance
----_ The Slice
---_ Programs
----_ Techniques
-----_ Mental
-----_ Twitch
-----_ Gesture
------_ Hand
------_ Arm
-----_ Hard
----_ DRM (Digital Reuse Mediator)
----_ Crypt Room
----_ Methods
-----_ Conceptualization
------_ Animation
------_ Atomization
-------_ Grind to Halt
------_ Reflections
------_ Possesion
-----_ Simulation
------_ Fields
-------_ Disco Elite
------_ Matter
-------_ Solid
-------_ Fluid
-----_ Matrix Signal
------_ Quick Crypt
------_ Input (Self and Others)
-------_ The Shell
-------_ Super-Senses
-------_ Lobotomycore
--------_ :3
------_ Output (Self and Others)
-------_ Illusions
-------_ Pseudonymization
-------_ Physical Abilites
'/

' Categorize all story elements

box Characters
    box Cobalt Saber
        participant "Elliot Fetterman"
        participant "Rafael Bosak"
        participant "Habib Khalil"
        participant "Manoj"
        participant "Anita"
    end box
end box

box Cobalt Saber
    participant "Model 49 (stolen)"
end box

box Altetro
    participant "Adrian Vue"
end box

box Marez
    participant "kern-marez-0934"
    participant "The Ardara (real)"
end box

box Olana
    participant "Altetro Building 50"
end box

box The Matrix
    participant "The Cipher"
    box Userland
        participant "Local Space"
        participant "The Crow's Den"
        participant "The Ardara"
    end box
end box

' Begin plot

== Narrative One ==

group Chapter 2: Into the Night

end

== Narrative Two ==

group Chapter 1: The Cipherists
    group Scene 1: kern-marez-0934
        "Adrian Vue" -> "Altetro Building 50": Realself
        "Adrian Vue" -> "The Ardara": Fakeself
        "Elliot Fetterman" -> "kern-marez-0934": Realself
        "Elliot Fetterman" -> "The Ardara": Fakeself (Vostok)
        "Rafael Bosak" -> "kern-marez-0934": Realself
        "Habib Khalil" -> "kern-marez-0934": Realself
        "Manoj" -> "kern-marez-0934": Realself
        "Manoj" -> "The Ardara": Fakeself (Apollo)
        "Anita" -> "kern-marez-0934": Realself
        "Anita" -> "The Ardara": Fakeself (Delta)
        activate "kern-marez-0934"
        note over "kern-marez-0934"
            Describe the server in detail
        end note
        "Elliot Fetterman" -> "kern-marez-0934": Is distracted by
        "Manoj" -> "Elliot Fetterman": Yells at to get on task
        "Elliot Fetterman" -> "Manoj": Whines at before getting on task
        "kern-marez-0934" -> "Model 49 (stolen)": Elliot, Rafael, and Habib (server tunnels)
        "Rafael Bosak" -> "Elliot Fetterman": Gives final brief of merc job
        "Rafael Bosak" -> "Habib Khalil": Gives final brief of merc job
        "Habib Khalil" -> "Rafael Bosak": Starts argument over pay
        "Elliot Fetterman" -> "Rafael Bosak": Backs Habib's argument
        "Rafael Bosak" -> "The Cipher": Changes subject to
        "Anita" -> "The Cipher": Uses synth-intuition to get the fry rate of
        "Anita" -> "Elliot Fetterman": Gives info to
        "Anita" -> "Elliot Fetterman": Discusses morality (bad) of the Cipher to
        "Manoj" -> "Anita": Discusses morality (good) of the Cipher to
        deactivate "kern-marez-0934"
    end
    group Scene 2: Car Ride
        activate "Model 49 (stolen)"
        "Elliot Fetterman" -> "Habib Khalil": "Damn Corporate Cipherists"
        "Elliot Fetterman" -> "Rafael Bosak": "Damn Corporate Cipherists"
        "Rafael Bosak" -> "Elliot Fetterman": Juxtaposes modern corporate Cipherists\nto the horrible things they did (Data War)
        "Rafael Bosak" -> "Habib Khalil": Juxtaposes modern corporate Cipherists\nto the horrible things they did (Data War)
        activate "The Ardara"
        "Adrian Vue" -> "Manoj": Asks what's wrong with Elliot
        "Manoj" -> "Adrian Vue": Responds with using fake double-signal senario
        "Elliot Fetterman" -> "The Ardara": Focuses more on fakeself (double-signal)
        "Elliot Fetterman" -> "Adrian Vue": Apologizes and backs up Manoj
        "Anita" -> "Adrian Vue": Asks about Cipher usage
        "Adrian Vue" -> "Anita": Responds and elaborates on non-pseudonymous Cipher use
        note over "Olana"
            Describe the city,
            chrome Olana,
            in detail
        end note
        deactivate "The Ardara"
        "Model 49 (stolen)" -> "Altetro Building 50": Elliot, Rafael, and Habib
        activate "Altetro Building 50"
        deactivate "Model 49 (stolen)"
    end
    group Scene 3: Fighting Through Altetro
        
    end
    group Scene 4: Adrian Vue
        "Adrian Vue" -> "Elliot Fetterman": Reveals that he owns the shell company which hired them for the hit
        "Adrian Vue" -> "Elliot Fetterman": Gives the real job: finding the identity of ihsotas
        deactivate "Altetro Building 50"
    end
end

' Elliot has knife to Adrians throat. In Matrix, he begs for his life by
' offering new job (finding out who ihsotas is) for more money

' Manoj, Anita, and Elliot (somwhat) help distract Adrian, because his expensive
' cybernetics, if actived on his realself, would be more difficult to defeat

@enduml