@startuml
@startmindmap Worldbuilding Map
!theme blueprint
+ The World
++_ Other Characters
+++_ Edmund Bosak
+++_ Fulco Lister
+++_ Jordan Hayes
+++_ Thath
+++_ The Flaberjackles
++_ Locations
+++_ America
+++_ Europe
+++_ Kernel City
++++_ Districts
+++++_ Marez
++++++_ The Ardara
++++++_ The Server Inferno
+++++_ Olana
++++++_ Chrome Buildings
+++++_ Herresh
++++++_ Poverty
++++_ MSEP
++++_ Dits
+++++_ Water Equivalent
++++_ State of Kernel
+++++_ Kernel Army
++++_ Synth-Bioluminescence
++++_ Kernelaid
++++_ Kernelese
+++_ India
+++_ China
++_ Pickerism
+++_ The Picker
+++_ Mathematical Model
++++_ Population of the Universe
++++_ Absolute/Relative Picker Time
++++_ Gamma
+++_ Oracles
+++_ Transcendentalism
++++_ The Transcendentalists' War
+++_ Cascade Theory
++++_ Sentience Obliteration
+++_ One True Harold
+++_ Yaqut
+++_ Cultish Behavior
++++_ Controllers
++++_ Changers
++++_ Choosers
+++++_ Super-Choosers
+++++_ Mega-Choosers
+++++_ Giga-Choosers
++_ Groups
+++_ Datism
++++_ Americans
+++++_ Dylan the Ricer
+++++_ Nick Mueller
+++++_ Taylor Walsh
++++_ CDO
+++++_ Guiying Yan
+++++_ Lewis Rodney
+++++_ Mei Liao
+++++_ Tao Lei
+++++_ Zhihao Dai
++++_ Europeans
+++++_ Faycal-Monique
+++++_ Marcel Thomas
++++_ The Trash
+++++_ Hamza
+++++_ Ina
+++++_ Nirmala Bulan
+++++_ Rashid Al Haddad
+++++_ Sakina Nagi
++++_ 3rd Worlders
++++_ Cobalt Saber
+++++_ Aleks Bosak (dead)
+++++_ Anita (new)
+++++_ Elliot Fetterman
+++++_ Habib Khalil
+++++_ Manoj (new)
+++++_ Rafael Bosak
+++_ Megacorps
++++_ Tachi-Odyne
+++++_ PMC
++++++_ Homeless
+++++++_ Synth-Organ Incentive Cycle
+++++++_ The Magazine Mechanism
++++++_ Alexandr Matveev
++++++_ Mark Mullens
++++++_ Chae-Yeong
++++_ Altetro
+++++_ Adrian Vue
+++++_ Felix Vue
++++_ Dark Ice Corporation
+++++_ Cryobed
+++++_ Cryotank
++++_ Zilla Arms
++++_ Verflux Studios
+++++_ Neurons
++++_ Endora
++++_ Kernel Biotech
+++++_ Rice Hack
+++++_ Interface
+++_ The Cicadas
++++_ Emil Rider
++++_ Lorreta the Cougar
+++_ Hyperchurches
++++_ John Smith
+++_ Drug Runners Of Marez
+++_ Interfaced
++++_ The Natrives
+++_ Un-Interfaced
--_ Internet
---_ Gospel of the Whores
---_ Matrix Compatibility
--_ Un-Interfaced Implants
---_ Exoskeletons
---_ Microweable
--_ AI
---_ Artifical Consciousness
---_ Cybernetic Model
----_ Manifold Manipulation
---_ Discrimination (Proompt)
----_ Harrison Arkwright
---_ Human Interfacing
----_ Host Detachment
-----_ Host Detachment Softorgans
---_ Softorgans
--_ Interface
---_ Installation Procedure
----_ Interface Pins
-----_ Heads
-----_ Artifical Guide Cells
-----_ Tubules
----_ Reservoirs
----_ Spider Robots
-----_ Anchoring
---_ Jack
----_ Wireless
----_ Wrist
---_ Neural Modem
----_ Modem Jacking
---_ Medicine
---_ Enhanced Combat
----_ Supression
-----_ Empathy
-----_ Pain
----_ Exaggeration
-----_ Reflexes
-----_ Senses
---_ Brain Plasticity
---_ Software
----_ Synth-Intuition
----_ Encryption
----_ Artifical Learning
-----_ Big Data (Easy)
------_ Languages
-----_ Small Data (Hard)
------_ Unique Skills
----_ Machine Control
----_ Pseudo-Meshing
-----_ Joining
----_ Hibernation 
---_ Implants
----_ Neural
-----_ Sensory (Internal)
-----_ Cognitive
-----_ Databank
----_ Physical
-----_ Sensory (External)
-----_ Endurance
-----_ Strength
---_ Bifurcation
----_ Vulgar Double-Signal
----_ Parallelism
----_ Mind-States
--_ Matrix
---_ Adam Task
----_ Hosts and Signals
-----_ Double and Mono-Signals
-----_ Severed Signal
------_ The Garbage Collector
------_ Exit Code
-----_ The Discriminator
-----_ Doowee
----_ Netspace
----_ Fee
-----_ ihsotas
-----_ The Traveler
------_ Mathematical Model
----_ Program Space
-----_ The Border
-----_ Rate Limit
------_ Datafreight
-----_ Dataforts
------_ Datastream
----_ Userland
-----_ Local Space
-----_ Estation/Estates
---_ Neurons
---_ Avatars
---_ Age (Realself:Matrix)
---_ Meshing
---_ Realself/Fakeself
---_ Locations
----_ Userland
-----_ The Crow's Den
-----_ Free Hub
-----_ Grandigi Hotel And Casino
-----_ Gardia
----_ Program Space
-----_ Hexridge
---_ Overlay Net
----_ The Cipher
-----_ Garlic Routing
-----_ Termination Rate
-----_ Plaintexters
-----_ Cipherists
---_ Overclocking
----_ Cryo
----_ Hyper Overclocking
-----_ Embeds And Embeddation
-----_ Hmeshing
------_ Bussard Mesh
-----_ Return Limit
----_ Merc
---_ Host Termination
----_ Frying (Overclocking)
----_ Lobotomycore/Massive Brainrot
----_ Signal Severance
----_ The Slice
---_ Programs
----_ Techniques
-----_ Mental
-----_ Twitch
-----_ Gesture
------_ Hand
------_ Arm
-----_ Hard
----_ DRM (Digital Reuse Mediator)
----_ Crypt Room
----_ Methods
-----_ Conceptualization
------_ Animation
------_ Atomization
-------_ Grind to Halt
------_ Reflections
------_ Possesion
-----_ Simulation
------_ Fields
-------_ Disco Elite
------_ Matter
-------_ Solid
-------_ Fluid
-----_ Matrix Signal
------_ Quick Crypt
------_ Input (Self and Others)
-------_ The Shell
-------_ Super-Senses
-------_ Lobotomycore
--------_ :3
------_ Output (Self and Others)
-------_ Illusions
-------_ Pseudonymization
-------_ Physical Abilites
@endmindmap
@enduml



